# Generated by Django 4.2.2 on 2023-07-01 14:28

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doc", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("name", models.TextField()),
                ("weight", models.IntegerField()),
                ("heigth", models.IntegerField()),
                ("gender", models.TextField()),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region=None
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "uuid",
                    models.UUIDField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("address", models.TextField()),
                ("past_allergies", models.TextField(blank=True)),
                ("past_operations", models.TextField(blank=True)),
                ("past_treatment", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medicine", models.TextField()),
                ("symptoms", models.TextField()),
                (
                    "doc_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="doc.doc"
                    ),
                ),
                (
                    "patient_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient.patient",
                    ),
                ),
            ],
        ),
    ]
